const tours = [
    {
      id:'abc',
      image: 'https://www.kayakbritishcolumbia.com/wp-content/uploads/2022/01/discovery-islands-249HI-kayaking.jpg',
      featured: true,
      title: 'Discovery Islands Kayaking Tour',
      location: 'Central Park West, USA',
      price: 39.0,
      rating: 4.4,
      days: 10,
      guests: 50,
      isFav: true,
      badges: 5,
    },
    {
        id:'abd',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh_Y_bZHyAAbW064WLmnMWMnLO2XDWob_BPw&s',
      featured: false,
      title: 'Mykonos and Santorini Tour',
      location: 'Central Park West, USA',
      price: 39.0,
      rating: 4.07,
      days: 10,
      guests: 50,
      isFav: false,
      badges: 4,
    },
    {
        id:'abf',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh_Y_bZHyAAbW064WLmnMWMnLO2XDWob_BPw&s',
      featured: false,
      title: 'The Metropolitan Museum Art',
      location: 'Central Park West NY, USA',
      price: 49.0,
      rating: 3.87,
      days: 10,
      guests: 60,
      isFav: false,
      badges: 5,
    },
    {
        id:'abg',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh_Y_bZHyAAbW064WLmnMWMnLO2XDWob_BPw&s',
        featured: false,
        title: 'The Metropolitan Museum Art',
        location: 'Central Park West NY, USA',
        price: 49.0,
        rating: 3.87,
        days: 10,
        guests: 60,
        isFav: false,
        badges: 5,
      },
      {
        id:'abz',
        image: 'https://www.kayakbritishcolumbia.com/wp-content/uploads/2022/01/discovery-islands-249HI-kayaking.jpg',
        featured: true,
        title: 'Discovery Islands Kayaking Tour',
        location: 'Central Park West, USA',
        price: 39.0,
        rating: 4.4,
        days: 10,
        guests: 50,
        isFav: true,
        badges: 5,
      },
      {
        id:'abx',
        image: 'https://www.kayakbritishcolumbia.com/wp-content/uploads/2022/01/discovery-islands-249HI-kayaking.jpg',
        featured: true,
        title: 'Discovery Islands Kayaking Tour',
        location: 'Central Park West, USA',
        price: 39.0,
        rating: 4.4,
        days: 10,
        guests: 50,
        isFav: true,
        badges: 5,
      },
  ];
   export default tours